### ISSUE TITLE
Avoid creating a fat JAR

### ISSUE THREAD

**Issue by MedKhem** [dkpro/dkpro-uby#156]
The actual build generates a fat JAR

**Comment by reckart** [comment]
The fat jar should be built!

**Comment by reckart** [comment]
The fat JAR is what users will download and use when they want to use ubycreate. They should not be using Eclipse to convert resources.

**Comment by MedKhem** [comment]
I see. I'm creating a new issue for that

**Comment by logological** [comment]
Has this issue been superseded by Issue 163?  Can I close it?

**Comment by reckart** [comment]
I think this can be closed.
