### ISSUE TITLE
Download link does not work

### ISSUE THREAD

**Issue by fnielsen** [dkpro/dkpro-uby#176]
Download link does not work, http://uby.ukp.informatik.tu-darmstadt.de/uby on eg https://dkpro.github.io/dkpro-uby/downloads/

**Comment by chmeyer** [comment]
Yes, you're right. Unfortunately the machine crashed severely and is currently being replaced. I'll keep posted once it is up and running again.

**Comment by fnielsen** [comment]
It seems to be working now.
