### ISSUE TITLE
Links to tutorials are dead

### ISSUE THREAD

**Issue by guilherme-salome** [dkpro/dkpro-uby#177]
On the page https://dkpro.github.io/dkpro-uby/ under `Learning UBY` the link to the tutorials are dead. Specifically:
- "Lexical Resources Tutorial held at GSCL 2015" is dead (https://uby.ukp.informatik.tu-darmstadt.deuby/gscl2015/);
- "UBY Tutorial held at TU Darmstadt in May 2015 (pdf)" is dead (https://uby.ukp.informatik.tu-darmstadt.deuby/dkpro-uby-tutorial-aiphes.pdf and https://uby.ukp.informatik.tu-darmstadt.deuby/dkpro-uby-tutorial-aiphes.zip)
- "UBY Tutorial held at GSCL 2013 (pdf)" links back to the UBY page, which links back to this repo for tutorials.
The only link actually working and pointing somewhere is https://code.google.com/archive/p/dkpro-tutorials/wikis/UbyTutorial2013.wiki

**Comment by guilherme-salome** [comment]
The link to database dumps 
http://uby.ukp.informatik.tu-darmstadt.de/uby is also dead

**Comment by reckart** [comment]
Unfortunately, the university had us migrate to a different content management system which killed all the existing "nice" URLs.

Some of the material is linked here: https://www.informatik.tu-darmstadt.de/ukp/research_6/data/lexical_resources/uby/index.en.jsp

Although it seems that even here, some links are presently dead :(

**Comment by guilherme-salome** [comment]
I was also searching that website for a tutorial on how to start using UBY but can't find anything.
There is a tutorial that links to [this page](https://zoidberg.ukp.informatik.tu-darmstadt.de/jenkins/job/Uby%20Documentation%20(GitHub)/de.tudarmstadt.ukp.uby$de.tudarmstadt.ukp.uby.doc-asl/doclinks/1/#db-import) but following it is not possible because the dumps are not available. Do you know if there is any easy to use API available somewhere? Thanks!

**Comment by reckart** [comment]
Here are some URLs I found:

* https://uby.ukp.informatik.tu-darmstadt.de/uby-browser/start
* https://uby.ukp.informatik.tu-darmstadt.de/uby-clarin-browser/start (this seems to be a newer one)

@chmeyer Anything to comment here, maybe regarding the an API?

@chmeyer I found the pre-build resources on the VM as well, but I don't know why they were moved off the public page. Do you know if they are incompatible with the latest Uby versions?

**Comment by randomnoob** [comment]
Hi,
I know the project is now abandoned, but does anyone know where I can get the DB dump? I've already exhausted every resources that I can.

**Comment by reckart** [comment]
I'll check... no promises...

**Comment by reckart** [comment]
@randomnoob Do you know which dumps you are looking for exactly?

**Comment by randomnoob** [comment]
> @randomnoob Do you know which dumps you are looking for exactly?

Hi,
I'm looking for one of these : 
- uby_open_0_6_0.sql.7z
- uby_open_0_6_0.sql.xz
- uby_open_0_7_0_20150507.sql.xz

The filenames comes from https://web.archive.org/web/20160122132248/http://uby.ukp.informatik.tu-darmstadt.de/uby/
Thank you!

**Comment by logological** [comment]
I can provide the following dumps if needed:

* uby_1_0_with_GN.sql
* uby_open_academic_0_3_0.sql
* uby_release_1_0.sql

Note that the first two of these contain the proprietary resource GermaNet, and so I can give them to you only if you have a GermaNet licence.  (If you do, you should send me your licence details and I'll verify these with the GermaNet folks.)

**Comment by reckart** [comment]
I have been able to salvage these from the archived Uby VM:

```
uby_open_0_7_0_20150507.sql.xz
uby_open_0_6_0.sql.xz
uby_open_0_6_0.sql.7z
```

But they lived in an "old" folder, so I do not know if they are compatible with the latest version of the code. Let me check where I can put them online for you...

**Comment by reckart** [comment]
@logological these" uby_open" files I mentioned above do not contain GermaNet, do they?

**Comment by logological** [comment]
@reckart: I can't say for sure without examining them.  But you could do so yourself: try grepping for `GN_Synset` on the decompressed SQL files.  If you get a lot of output, then the dump contains GermaNet.

**Comment by reckart** [comment]
```
$ xzgrep "GN_Synset" uby_open_0_7_0_20150507.sql.xz
$ xzgrep "GN_Synset" uby_open_0_6_0.sql.xz
$
```

Looks safe.

**Comment by reckart** [comment]
* https://public.ukp.informatik.tu-darmstadt.de/UBY/uby_open_0_6_0.sql.7z
* https://public.ukp.informatik.tu-darmstadt.de/UBY/uby_open_0_6_0.sql.xz
* https://public.ukp.informatik.tu-darmstadt.de/UBY/uby_open_0_7_0_20150507.sql.xz

**Comment by logological** [comment]
@reckart Would you also like me to send you uby_release_1_0.sql to post there?

Come to think of it, shouldn't all these go on [TUdatalib](https://tudatalib.ulb.tu-darmstadt.de/)?  Most of the other UKP data sets and resources are already there.

**Comment by reckart** [comment]
It would be good if there were on TUdatalib. Could you provide descriptions for the datasets? 

I have a `uby_release_1_0.sql.7z` also that I could put on the server. I assume that's the same you have.

**Comment by logological** [comment]
Yes, that's probably the same version I have.  Below is a generic description that can be used for all the databases; unfortunately, I don't know which versions of the resources are included in which versions of the UBY database.

```
UBY is a large-scale lexical-semantic resource for natural language processing (NLP) based on the ISO standard Lexical Markup Framework (LMF).  The UBY database distributed here integrates the English- and German-language lexical-semantic resources listed below.  (UBY is also capable of integrating GermaNet, but we do not include it here as it is subject to a proprietary licence.)  We also separately distribute [software for accessing the database](https://dkpro.github.io/dkpro-uby/).

Integrated resources (only including resources with open licences):

- English WordNet, Wiktionary, Wikipedia, FrameNet and the syntactically rich VerbNet
- German Wikipedia, Wiktionary, the syntactically rich IMSLex-Subcat, as well as multilingual OmegaWiki

Integrated alignment resources:

External alignments:
- WordFrameNet
- Semlink VerbNet - FrameNet mapping

Alignments created by UKP Lab:
- WordNet 3.0 - Wiktionary English alignment
- WordNet 3.0 - OmegaWiki German alignment
- Wiktionary English - FrameNet alignment
- Wiktionary English - OmegaWiki English alignment
- WordNet - Wikipedia English alignment
```

If you need further metadata for the TUdatalib record (papers to cite, licence, etc.), you can probably copy them from the [DKPro UBY page](https://dkpro.github.io/dkpro-uby/) and/or the [UBY database licence of 2015-05-22](https://web.archive.org/web/20150522024304/http://uby.ukp.informatik.tu-darmstadt.de/uby/LICENSE2015-05-13.txt).

**Comment by reckart** [comment]
Thanks... looking into it...

**Comment by reckart** [comment]
Here is the TUdatalib page: https://tudatalib.ulb.tu-darmstadt.de/handle/tudatalib/2941

@logological Does that look good to you?

**Comment by logological** [comment]
Yep.

**Comment by reckart** [comment]
Ok, then I believe we can close this issue. 🎉
